######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 8 01:51:11 2009
######################################################################

TEMPLATE = app
TARGET = dbus-test
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qdbus
# Input
SOURCES += main.cpp
