/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -a linkhomeadaptor -c LinkHomeAdaptor tv.neuros.LinkHome.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "linkhomeadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class LinkHomeAdaptor
 */

LinkHomeAdaptor::LinkHomeAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

LinkHomeAdaptor::~LinkHomeAdaptor()
{
    // destructor
}

void LinkHomeAdaptor::AppStart(const QString &path)
{
    // handle method call tv.neuros.LinkHome.AppStart
    QMetaObject::invokeMethod(parent(), "AppStart", Q_ARG(QString, path));
}

void LinkHomeAdaptor::AppStart(const QString &path, const QStringList &args)
{
    // handle method call tv.neuros.LinkHome.AppStart
    QMetaObject::invokeMethod(parent(), "AppStart", Q_ARG(QString, path), Q_ARG(QStringList, args));
}

void LinkHomeAdaptor::AppStart(const QString &path, const QStringList &args, const QString &wd)
{
    // handle method call tv.neuros.LinkHome.AppStart
    QMetaObject::invokeMethod(parent(), "AppStart", Q_ARG(QString, path), Q_ARG(QStringList, args), Q_ARG(QString, wd));
}

void LinkHomeAdaptor::Test()
{
    // handle method call tv.neuros.LinkHome.Test
    QMetaObject::invokeMethod(parent(), "Test");
}

